name: CI
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '12', '14', '16' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run build
      - name: Test
        env:
          SITE: SHEPHERD_DOT_DIRECTORY="./fixtures/artifacts/.shepherd"
        run: npm run test
